[package]
name = "tinymatrix"
version = "0.1.0"
edition = "2021"
description = "A small library to operate with some linear algebra functions"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/kaikecarlos/tiny-matrix"

[dependencies]
